### ISSUE TITLE
Avoid having plenty of deploy buckets

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/public-cdn#2]
Try to find a way to hide/not have plenty of deployment buckets from CloudFormation when using Serverless

We just want to see the actual bucket with actual content on S3

**Comment by Holger-Will** [comment]
you can delete all deployment buckets already in Existence and create one common bucket for all deployments.

https://forum.serverless.com/t/delete-s3-buckets-after-deployment/5208

**Comment by alexlemaire** [comment]
Changes applied, we should now have only one bucket called `kaskadi-serverless-deployment-bucket` where all deployments are done.

Buckets were actually gone a few minutes ago but seems to have reappear without being actually there. When I'm trying to open one I'm getting an error that there is no data (not even bucket config) and if I try and delete it nothing is happening.

So I think there is some kind of issue with AWS S3 UI for now and everything should get back to normal soon.

Closing for now!
